LAYER_SPECS = 'layer_specs'
ACTIVATION = 'activation'
BATCH = 'batch_size'
EPOCHS = 'epochs'
EARLY_STOP = 'early_stop'
ESTOP_THRESH = 'early_stop_epoch'
WEIGHT_DECAY = 'weight_decay'
MOMENTUM = 'momentum'
GAMMA = 'momentum_gamma'
LR = 'learning_rate'
RESUME = 'resume'
START_EPOCH = 'start_epoch'
BEST_LOSS = 'best_loss'
MODE = 'mode'
MODEL_DIR = 'model_dir'
TRAIN = 'train'; VAL = 'val'; TEST = 'test'
IMG = 'images'; LBL = 'labels'
TRANSFORM = 'transform'
INPUT_SIZE = 'input_size'
COLOR = 'color'
PRETRAINED = 'pretrained'
FREEZE = 'freeze'
WEIGHTED = 'weighted_loss'